### PR TITLE
Contact

### PR DESCRIPTION
**Pull request by iamdustan**
cc @jordancardwell. Still more work to do, but it’s enough to get the heart of it out there before the weekend.

screen shot 2015-05-22 at 2 42 03 pm

### CODE REVIEW

**Comment by jordancardwell** [comment]
@iamdustan doesn't look like I have write access to merge on this repo

**Comment by ruprict** [comment]
@jordancardwell Try now.

**Comment by iamdustan** [comment]
Any commentary on the implementation?

**Comment by jordancardwell** [comment]
@ruprict Yeah I can merge now.. grazi

**Comment by iamdustan** [comment]
:thumbsup: updated

**Pull request merged**
